# Generated by Django 5.2.7 on 2026-02-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_curso', models.CharField(max_length=20, unique=True)),
                ('nome_curso', models.CharField(max_length=255)),
                ('nivel_curso', models.CharField(choices=[('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação')], max_length=20)),
                ('turno_curso', models.CharField(blank=True, choices=[('Integral', 'Integral'), ('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Diurno', 'Diurno')], max_length=20, null=True)),
                ('modalidade_curso', models.CharField(blank=True, help_text='Presencial, EAD, etc.', max_length=45, null=True)),
                ('area_conhecimento_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionamento_curso', models.CharField(choices=[('Em atividade', 'Em atividade'), ('Inativo', 'Inativo'), ('Suspenso', 'Suspenso')], default='Em atividade', max_length=20)),
                ('grau_academico', models.CharField(blank=True, help_text='Bacharelado, Licenciatura...', max_length=100, null=True)),
                ('ato_autorizacao_curso', models.TextField(blank=True, null=True)),
                ('ato_reconhecimento_curso', models.TextField(blank=True, null=True)),
                ('conceito_mec_curso', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_disciplina', models.CharField(max_length=30, unique=True)),
                ('nome_disciplina', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('nota_minima_aprovacao', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('ementa', models.TextField(blank=True, null=True)),
                ('programa', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('avaliacao', models.TextField(blank=True, null=True)),
                ('bibliografia_basica', models.TextField(blank=True, null=True)),
                ('bibliografia_complementar', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=255)),
                ('cpf_usuario', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id_curriculo', models.AutoField(primary_key=True, serialize=False)),
                ('versao', models.CharField(help_text='Ex: Versão 01', max_length=50)),
                ('ano_inicio', models.IntegerField()),
                ('semestre_inicio', models.IntegerField(help_text='1 ou 2')),
                ('regime_letivo', models.CharField(choices=[('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Semestral', max_length=20)),
                ('num_periodos_ideal', models.IntegerField(blank=True, null=True)),
                ('total_creditos', models.IntegerField(blank=True, null=True)),
                ('carga_horaria_total', models.IntegerField(blank=True, null=True)),
                ('carga_horaria_min_periodo', models.IntegerField(default=30)),
                ('carga_horaria_max_periodo', models.IntegerField(default=600)),
                ('num_trancamentos_totais', models.IntegerField(default=3)),
                ('num_trancamentos_parciais', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('Corrente', 'Corrente'), ('Ativa Anterior', 'Ativa Anterior'), ('Inativo', 'Inativo')], default='Ativa Anterior', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculos', to='base.curso')),
            ],
            options={
                'db_table': 'curriculo',
            },
        ),
        migrations.CreateModel(
            name='CurriculoDisciplina',
            fields=[
                ('id_curriculo_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.IntegerField(help_text='Período em que a disciplina é oferecida')),
                ('tipo_disciplina', models.CharField(choices=[('Obrigatória', 'Obrigatória'), ('Optativa', 'Optativa'), ('Eletiva', 'Eletiva')], default='Obrigatória', max_length=20)),
                ('ordem_exibicao', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.curriculo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.disciplina')),
            ],
            options={
                'db_table': 'curriculo_disciplina',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_docente', models.CharField(max_length=255)),
                ('titulacao_docente', models.CharField(blank=True, choices=[('Graduação', 'Graduação'), ('Especialização', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-Doutorado', 'Pós-Doutorado')], max_length=50, null=True)),
                ('centro_lotacao', models.CharField(blank=True, max_length=45, null=True)),
                ('cargo_docente', models.CharField(blank=True, choices=[('Professor Adjunto', 'Professor Adjunto'), ('Professor Assistente', 'Professor Assistente'), ('Professor Titular', 'Professor Titular'), ('Professor Substituto', 'Professor Substituto')], max_length=50, null=True)),
                ('jornada_docente', models.IntegerField(blank=True, help_text='Horas semanais', null=True)),
                ('tempo_casa_docente', models.IntegerField(blank=True, help_text='Anos na instituição', null=True)),
                ('email_docente', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'docente',
                'indexes': [models.Index(fields=['nome_docente'], name='idx_nome_docente')],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(blank=True, db_column='coordenador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.docente'),
        ),
        migrations.CreateModel(
            name='DocenteDisciplina',
            fields=[
                ('id_docente_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField(help_text='1 ou 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.disciplina')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.docente')),
            ],
            options={
                'db_table': 'docente_disciplina',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCurso',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_documento', models.CharField(choices=[('Regulamento', 'Regulamento'), ('Portaria', 'Portaria'), ('Resolução', 'Resolução'), ('Outro', 'Outro')], default='Outro', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.curso')),
            ],
            options={
                'db_table': 'documento_curso',
            },
        ),
        migrations.CreateModel(
            name='PPC',
            fields=[
                ('id_ppc', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('arquivo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.curriculo')),
            ],
            options={
                'db_table': 'ppc',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id_unidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_unidade', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'unidade',
                'indexes': [models.Index(fields=['sigla'], name='idx_sigla_unidade')],
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.unidade'),
        ),
        migrations.AddIndex(
            model_name='curriculo',
            index=models.Index(fields=['status'], name='idx_status_curriculo'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculo',
            unique_together={('curso', 'versao', 'ano_inicio', 'semestre_inicio')},
        ),
        migrations.AddIndex(
            model_name='curriculodisciplina',
            index=models.Index(fields=['periodo'], name='idx_periodo_cd'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculodisciplina',
            unique_together={('curriculo', 'disciplina')},
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['codigo_curso'], name='idx_codigo_curso'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['nome_curso'], name='idx_nome_curso'),
        ),
        migrations.AddIndex(
            model_name='docentedisciplina',
            index=models.Index(fields=['ano', 'semestre'], name='idx_ano_semestre_dd'),
        ),
        migrations.AddIndex(
            model_name='disciplina',
            index=models.Index(fields=['codigo_disciplina'], name='idx_codigo_disciplina'),
        ),
        migrations.AddIndex(
            model_name='disciplina',
            index=models.Index(fields=['nome_disciplina'], name='idx_nome_disciplina'),
        ),
    ]
