# Generated by Django 6.0.2 on 2026-03-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_curso_inserido_manualmente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoEdicaoUsuario',
            fields=[
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='edicao_usuario', serialize=False, to='base.curso')),
                ('nome_curso', models.CharField(blank=True, max_length=255, null=True)),
                ('turno_curso', models.CharField(blank=True, choices=[('Integral', 'Integral'), ('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Diurno', 'Diurno')], max_length=20, null=True)),
                ('modalidade_curso', models.CharField(blank=True, max_length=45, null=True)),
                ('area_conhecimento_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionamento_curso', models.CharField(blank=True, choices=[('Em atividade', 'Em atividade'), ('Inativo', 'Inativo'), ('Suspenso', 'Suspenso')], max_length=20, null=True)),
                ('grau_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('ato_autorizacao_curso', models.TextField(blank=True, null=True)),
                ('ato_reconhecimento_curso', models.TextField(blank=True, null=True)),
                ('conceito_mec_curso', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.usuario')),
            ],
            options={
                'db_table': 'curso_edicao_usuario',
            },
        ),
    ]
